FROM python:3.8-slim-buster
WORKDIR /the/workdir/path
COPY requirements.txt .
RUN python -m pip install -r requirements.txt
COPY . /app
EXPOSE 5000
CMD ["gunicorn", "works=3", "--bind", "0.0.0.0:5000","-c", "config.py", "app:app"]
